context("test-01-chart.R: test chart")

chart1 <- new(acmacs.Chart, "2004-3.ace")
test_that("name", { expect_equal(chart1$name, "Labels") })
test_that("number of antigens", { expect_equal(chart1$number_of_antigens, 22) })
test_that("number of sera", { expect_equal(chart1$number_of_sera, 6) })
test_that("number of points", { expect_equal(chart1$number_of_points, chart1$number_of_antigens + chart1$number_of_sera) })
test_that("number of projections", { expect_equal(chart1$number_of_projections, 1) })
test_that("number of layers", { expect_equal(chart1$titers$number_of_layers, 0) })
chart1$remove_layers()
test_that("number of layers upon layers removal", { expect_equal(chart1$titers$number_of_layers, 0) })

test_that("column bases", { expect_equal(chart1$column_bases(), c(7,8,8,8,8,8)) })
chart1$set_column_bases(c(10,10,10,10,10,10))
test_that("column bases after enforcing", { expect_equal(chart1$column_bases(), c(10,10,10,10,10,10)) })
# chart1$save("2004-3.forced-cb.ace")
chart1$set_column_basis(2, 11)
test_that("column bases after enforcing and updating", { expect_equal(chart1$column_bases(), c(10,11,10,10,10,10)) })

chart2 <- new(acmacs.Chart, "cdc-h1pdm-2009.acd1.bz2")
test_that("name", { expect_equal(chart2$name, "") })
test_that("number of antigens", { expect_equal(chart2$number_of_antigens, 303) })
test_that("number of sera", { expect_equal(chart2$number_of_sera, 31) })
test_that("number of points", { expect_equal(chart2$number_of_points, chart2$number_of_antigens + chart2$number_of_sera) })
test_that("number of projections", { expect_equal(chart2$number_of_projections, 1) })
test_that("column bases", { expect_equal(chart2$column_bases(), c(7.33360262826828, 9, 9, 8, 9, 9, 7, 7, 7, 8, 9, 9, 9, 9, 11, 8, 10, 10, 9, 9, 7, 9, 9, 8, 10, 11, 11, 10, 10, 8, 9)) })
test_that("number of layers", { expect_equal(chart2$titers$number_of_layers, 6) })
chart2$remove_layers()
test_that("number of layers upon layers removal", { expect_equal(chart2$titers$number_of_layers, 0) })
chart2_new_name = "chart2"
chart2$name = chart2_new_name
test_that("name", { expect_equal(chart2$name, chart2_new_name) })
test_that("column bases (-2)", { expect_that(chart2$column_bases(-2), throws_error()) })
test_that("column bases (1000)", { expect_that(chart2$column_bases(1000), throws_error()) })

# cloning
output_filename_ace <- "/tmp/acmacs.r.test01.ace"
chart1 <- new(acmacs.Chart, "2004-3.ace")
chart2 <- chart1$clone()
chart2$save(output_filename_ace)
chart3 <- new(acmacs.Chart, output_filename_ace)
unlink(c(output_filename_ace))
test_that("cloned chart name", { expect_equal(chart1$name, chart3$name) })
test_that("cloned number of antigens", { expect_equal(chart1$number_of_antigens, chart3$number_of_antigens) })
test_that("cloned number of sera", { expect_equal(chart1$number_of_sera, chart3$number_of_sera) })
test_that("cloned number of points", { expect_equal(chart1$number_of_points, chart3$number_of_points) })
test_that("cloned number of projections", { expect_equal(chart1$number_of_projections, chart3$number_of_projections) })
test_that("cloned column bases", { expect_equal(chart1$column_bases(), chart3$column_bases()) })
test_that("cloned number of layers", { expect_equal(chart1$titers$number_of_layers, chart3$titers$number_of_layers) })

# new layout
chart1 <- new(acmacs.Chart, "2004-3.ace")
chart1$remove_all_projections()
test_that("upon removal all projections", { expect_equal(chart1$number_of_projections, 0) })
chart1$new_projection("none", 2)
chart1$new_projection("none", 2, "sample-optimization")
chart1$new_projection("none", 2, "table-max-distance")
chart1$new_projection("none", 2, "current-layout-area")
test_that("upon creating randomized projections", { expect_equal(chart1$number_of_projections, 4) })
chart1$remove_all_projections()
test_that("upon removal all projections (again)", { expect_equal(chart1$number_of_projections, 0) })
prj1 <- chart1$new_projection_with_layout("none", matrix(1:((chart1$number_of_antigens + chart1$number_of_sera)*2), ncol=2, byrow=TRUE))
test_that("number of dimensions for new projection with layout", expect_equal(prj1$number_of_dimensions, 2))
test_that("stress for new projection with layout", expect_equal(prj1$stress, 205094.9975, tolerance=1e-3))
prj1$relax()
test_that("stress after relaxing projection with non-random layout", expect_equal(prj1$stress, 79.7583, tolerance=1e-3))

# extension fields
library(jsonlite)
chart5 <- new(acmacs.Chart, "2004-3.ace")
test_that("extension field: initial", { expect_equal(chart5$extension_field("test-1"), NA_character_) })
ext.data.1 <- data.frame(no=c(15:19), name=c("Fridrich", "Wilhelm", "Barbarossa", "Sonnenkoenig", "Oedipa"), stringsAsFactors=FALSE)
chart5$set_extension_field("test-1", toJSON(ext.data.1))
ext.data.1.read <- fromJSON(chart5$extension_field("test-1"))
test_that("extension field: ext.data.1.read$no", { expect_equal(ext.data.1.read$no, ext.data.1$no) })
test_that("extension field: ext.data.1.read$name", { expect_true(all.equal(ext.data.1.read$name, ext.data.1$name)) })
chart5$save(output_filename_ace)
chart6 <- new(acmacs.Chart, output_filename_ace)
unlink(c(output_filename_ace))
ext.data.2.read <- fromJSON(chart6$extension_field("test-1"))
test_that("extension field: ext.data.1.read$no", { expect_equal(ext.data.2.read$no, ext.data.1$no) })
test_that("extension field: ext.data.1.read$name", { expect_true(all.equal(ext.data.2.read$name, ext.data.1$name)) })
