context("Test chart merge")

chart1 <- new(acmacs.Chart, "to-merge-1.ace")
chart2 <- new(acmacs.Chart, "to-merge-2.ace")
merge_type2 <- new(acmacs.Chart, "merge-type2.ace")
merge1 <- acmacs.merge.1(chart1, chart2)
test_that("merge1 number of antigens", { expect_equal(merge1$number_of_antigens, merge_type2$number_of_antigens) })
test_that("merge1 number of sera", { expect_equal(merge1$number_of_sera, merge_type2$number_of_sera) })
test_that("merge1 number of layers", { expect_equal(merge1$titers$number_of_layers, merge_type2$titers$number_of_layers) })
test_that("merge1 column bases", { expect_equal(merge1$column_bases(), merge_type2$column_bases()) })

chart1 <- new(acmacs.Chart, "to-merge-1.ace")
chart2 <- new(acmacs.Chart, "to-merge-2.ace")
merge2 <- acmacs.merge.2(chart1, chart2)
test_that("merge2 number of antigens", { expect_equal(merge2$number_of_antigens, merge_type2$number_of_antigens) })
test_that("merge2 number of sera", { expect_equal(merge2$number_of_sera, merge_type2$number_of_sera) })
test_that("merge2 number of layers", { expect_equal(merge2$titers$number_of_layers, merge_type2$titers$number_of_layers) })
test_that("merge2 column bases", { expect_equal(merge2$column_bases(), merge_type2$column_bases()) })
test_that("merge2 stress", { expect_equal(merge2$projections[[1]]$stress, merge_type2$projections[[1]]$stress) })
merge2$relax_incremental(100, FALSE)
# print(paste("merge2 stress: ", merge2$projections[[1]]$stress))
test_that("merge2 stress upon relaxing", { expect_equal(merge2$projections[[1]]$stress, 118.998, tolerance=1e-3) })

merge3 <- acmacs.merge.3(chart1, chart2)
merge_type3 <- new(acmacs.Chart, "merge-type3.ace")
test_that("merge3 number of antigens", { expect_equal(merge3$number_of_antigens, merge_type3$number_of_antigens) })
test_that("merge3 number of sera", { expect_equal(merge3$number_of_sera, merge_type3$number_of_sera) })
test_that("merge3 number of layers", { expect_equal(merge3$titers$number_of_layers, merge_type3$titers$number_of_layers) })
test_that("merge3 column bases", { expect_equal(merge3$column_bases(), merge_type3$column_bases()) })
test_that("merge3 stress", { expect_equal(merge3$projections[[1]]$stress, merge_type3$projections[[1]]$stress) })

merge4 <- acmacs.merge.4(chart1, chart2)
merge_type4 <- new(acmacs.Chart, "merge-type4.ace")
test_that("merge4 number of antigens", { expect_equal(merge4$number_of_antigens, merge_type4$number_of_antigens) })
test_that("merge4 number of sera", { expect_equal(merge4$number_of_sera, merge_type4$number_of_sera) })
test_that("merge4 number of layers", { expect_equal(merge4$titers$number_of_layers, merge_type4$titers$number_of_layers) })
test_that("merge4 column bases", { expect_equal(merge4$column_bases(), merge_type4$column_bases()) })
test_that("merge4 stress", { expect_equal(merge4$projections[[1]]$stress, merge_type4$projections[[1]]$stress) })

merge4 <- acmacs.merge.5(chart1, chart2)
merge_type5 <- new(acmacs.Chart, "merge-type5.ace")
test_that("merge4 number of antigens", { expect_equal(merge4$number_of_antigens, merge_type5$number_of_antigens) })
test_that("merge4 number of sera", { expect_equal(merge4$number_of_sera, merge_type5$number_of_sera) })
test_that("merge4 number of layers", { expect_equal(merge4$titers$number_of_layers, merge_type5$titers$number_of_layers) })
test_that("merge4 column bases", { expect_equal(merge4$column_bases(), merge_type5$column_bases()) })
test_that("merge4 stress", { expect_equal(merge4$projections[[1]]$stress, merge_type5$projections[[1]]$stress) })

report <- acmacs.merge_report(chart1, chart2)
# cat(report)
