context("Test chart")

chart1 <- new(acmacs.Chart, "2004-3.ace")
test_that("number of antigens", { expect_equal(chart1$number_of_antigens, 22) })
test_that("number of sera", { expect_equal(chart1$number_of_sera, 6) })
test_that("number of points", { expect_equal(chart1$number_of_points, chart1$number_of_antigens + chart1$number_of_sera) })
test_that("number of projections", { expect_equal(chart1$number_of_projections, 1) })
test_that("number of layers", { expect_equal(chart1$titers$number_of_layers, 0) })
chart1$remove_layers()
test_that("number of layers upon layers removal", { expect_equal(chart1$titers$number_of_layers, 0) })

chart2 <- new(acmacs.Chart, "cdc-h1pdm-2009.acd1.bz2")
test_that("number of antigens", { expect_equal(chart2$number_of_antigens, 303) })
test_that("number of sera", { expect_equal(chart2$number_of_sera, 31) })
test_that("number of points", { expect_equal(chart2$number_of_points, chart2$number_of_antigens + chart2$number_of_sera) })
test_that("number of projections", { expect_equal(chart2$number_of_projections, 1) })
test_that("column bases", { expect_equal(chart2$column_bases(), c(7.33360262826828, 9, 9, 8, 9, 9, 7, 7, 7, 8, 9, 9, 9, 9, 11, 8, 10, 10, 9, 9, 7, 9, 9, 8, 10, 11, 11, 10, 10, 8, 9)) })
test_that("number of layers", { expect_equal(chart2$titers$number_of_layers, 6) })
chart2$remove_layers()
test_that("number of layers upon layers removal", { expect_equal(chart2$titers$number_of_layers, 0) })

# cloning
output_filename_ace <- "/tmp/acmacs.r.test01.ace"
chart1 <- new(acmacs.Chart, "2004-3.ace")
chart2 <- chart1$clone()
chart2$save(output_filename_ace)
chart3 <- new(acmacs.Chart, output_filename_ace)
unlink(c(output_filename_ace))
test_that("cloned chart name", { expect_equal(chart1$name, chart3$name) })
test_that("cloned number of antigens", { expect_equal(chart1$number_of_antigens, chart3$number_of_antigens) })
test_that("cloned number of sera", { expect_equal(chart1$number_of_sera, chart3$number_of_sera) })
test_that("cloned number of points", { expect_equal(chart1$number_of_points, chart3$number_of_points) })
test_that("cloned number of projections", { expect_equal(chart1$number_of_projections, chart3$number_of_projections) })
test_that("cloned column bases", { expect_equal(chart1$column_bases(), chart3$column_bases()) })
test_that("cloned number of layers", { expect_equal(chart1$titers$number_of_layers, chart3$titers$number_of_layers) })
