context("Test creating chart from scratch")

chart1 <- new(acmacs.Chart, 5, 3)
test_that("number of antigens", { expect_equal(chart1$number_of_antigens, 5) })
test_that("number of sera", { expect_equal(chart1$number_of_sera, 3) })
test_that("number of points", { expect_equal(chart1$number_of_points, chart1$number_of_antigens + chart1$number_of_sera) })
test_that("number of projections", { expect_equal(chart1$number_of_projections, 0) })
test_that("empty name", { expect_equal(chart1$name, "") })
test_that("info", { expect_equal(chart1$info, "Antigens:5 Sera:3\nProjections: 0") })
test_that("empty lineage", { expect_equal(chart1$lineage, "") })
